### ISSUE TITLE
problem with effortless

### ISSUE THREAD

**Issue by mrcisdaduntman** [Low-Drag-MC/Photon#5]
Error: java.lang.NullPointerException: Cannot invoke "java.io.File.getName()" because "this.f_10203_" is null
[crash-2023-07-03_09.16.36-client.txt](https://github.com/Low-Drag-MC/Photon/files/11938728/crash-2023-07-03_09.16.36-client.txt)

**Comment by Yefancy** [comment]
![image](https://github.com/Low-Drag-MC/Photon/assets/18493855/0270642b-02fc-439c-a6ec-f3f8347d79e8)

hi dude, you didnt install photon.
You crashed and ask for my help. how can I help you? how to install the minecraft?

**Comment by Yefancy** [comment]
besides, you were using the forge 43.0.0
